# Generated by Django 3.2.9 on 2021-11-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.CharField(max_length=100, verbose_name="User's link")),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's link",
                'verbose_name_plural': "User's links",
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=17)),
                ('long_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_link', to='main.longlink')),
            ],
            options={
                'verbose_name': 'Short link',
                'verbose_name_plural': 'Short links',
            },
        ),
    ]
