# Generated by Django 3.2.9 on 2021-11-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_link_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='username',
            new_name='user',
        ),
    ]
